### ISSUE TITLE
Feedback on Iteration Plan EL1

### ISSUE THREAD

**Issue by mapfap** [SSD2015/TeamManat#10]
Your [plan] (https://github.com/SSD2015/TeamManat/blob/master/Iteration%20Plan%20EL1.md) looks OK.

But I have questions about your software design. It seems that you completely separate client and server. This [issue](https://github.com/SSD2015/TeamManat/issues/2) tells that there will be 'Voting API'. You are going to create a Web Service and let mobile app send request to server? Maybe that's too much work?

Since you're using Play, I think it's easier to just do it as a web application. You can just [pass the variables to HTML view from controllers](https://docs.google.com/document/d/1u5nmmmio4bIgbIiZJB_UmXP9gX_ZrWBqEIguHj5Whhs/edit#heading=h.i9xsiqhv0dib).

(This is just a suggestion anyway)

**Comment by chinclubi** [comment]
อ่อ ขอบคุณครับพี่ คิดมากไปหนอ่ย เดี๋ยวลบออกดีกว่าครับ

**Comment by chinclubi** [comment]
Thank you for your advice , I am overthinking. lol
Web application looks really easy. :3
