### ISSUE TITLE
Web Deployment

### ISSUE THREAD

**Issue by OngOngoing** [SSD2015/TeamManat#6]

**Comment by chinclubi** [comment]
I can't make it online. I installed everything completely on cloud platform but there are some technical issue that I need help from professional.
![untitled](https://cloud.githubusercontent.com/assets/5950717/6493223/d7c5fb9a-c2eb-11e4-8b4b-44ffac89e975.png)
In this picture, application was built and successfully. It deployed on 128.199.68.147:49163 but i can't access to that ip-address.
![untitled](https://cloud.githubusercontent.com/assets/5950717/6493330/8585c508-c2ec-11e4-98ba-13776fcf3c83.png)
This is log from my application. I have no idea to fix this problem.

**Comment by chinclubi** [comment]
thank, problem was solved :D
